name: .NET

concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ master ] # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  #[BUILD]
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    timeout-minutes: 10
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: |
            6.0.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore $GITHUB_WORKSPACE/src/PotionsPlus.sln --nologo -v d

      - name: Build (w/o Version Bump)
        run: dotnet build $GITHUB_WORKSPACE/src/PotionsPlus.sln -c Release --nologo -v n

      - name: Save Zip Package
        if: ${{ !inputs.is-nuget-package }}
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/src/PotionsPlus/bin/Release/*.zip
          name: zip-package
          retention-days: 7
